### ISSUE TITLE
spacewalk-data-fsck  to run on python3

### ISSUE THREAD

**Issue by sbluhm** [sbluhm/uyuni#107]
```
# spacewalk-data-fsck  
Traceback (most recent call last):
  File "/usr/bin/spacewalk-data-fsck", line 423, in <module>
    exit_value += check_db_vs_disk(options)
  File "/usr/bin/spacewalk-data-fsck", line 91, in check_db_vs_disk
    query = package_query(options)
  File "/usr/bin/spacewalk-data-fsck", line 73, in package_query
    if is_sha256_capable():
  File "/usr/bin/spacewalk-data-fsck", line 48, in is_sha256_capable
    cmp = rpm.labelCompare([h['name'].decode("utf-8"), h['version'].decode("utf-8"), h['release'].decode("utf-8")],
AttributeError: 'str' object has no attribute 'decode'

```

**Comment by sbluhm** [comment]
duplicate
