### ISSUE TITLE
spacewalk-data-fsck does not work on python3

### ISSUE THREAD

**Issue by sbluhm** [sbluhm/uyuni#110]
### Problem description

# spacewalk-data-fsck
Traceback (most recent call last):
  File "/usr/bin/spacewalk-data-fsck", line 423, in <module>
    exit_value += check_db_vs_disk(options)
  File "/usr/bin/spacewalk-data-fsck", line 91, in check_db_vs_disk
    query = package_query(options)
  File "/usr/bin/spacewalk-data-fsck", line 73, in package_query
    if is_sha256_capable():
  File "/usr/bin/spacewalk-data-fsck", line 48, in is_sha256_capable
    cmp = rpm.labelCompare([h['name'].decode("utf-8"), h['version'].decode("utf-8"), h['release'].decode("utf-8")],
AttributeError: 'str' object has no attribute 'decode'

### Steps to reproduce

1.
2.
3.
...
above

### Uyuni version

```bash
master
```

**Comment by sbluhm** [comment]
nothing to do with p3. rpm returns different types despite same rpm version.

this works on EL

import rpm
ts = rpm.TransactionSet()
mi = ts.dbMatch('Providename', 'spacewalk-schema')
cmp = -1
h = next(mi)
cmp = rpm.labelCompare((h['name'], h['version'], h['release']),
                               (h['name'], '0.8.1', '1'))

**Comment by sbluhm** [comment]
PR7086
