### ISSUE TITLE
ImportError: cannot import name 'wait' from partially initialized module 'multiprocessing.connection' (most likely due to a circular import)

### ISSUE THREAD

**Issue by sbluhm** [sbluhm/uyuni#114]
```
2023-06-21 14:00:00,613 [tornado.application:353 ][ERROR   ][4136974] Future <salt.ext.tornado.concurrent.Future object at 0x7f1ac546f5e0> exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/lib/python3.9/site-packages/salt/utils/process.py", line 631, in run
    time.sleep(10)
  File "/usr/lib/python3.9/site-packages/salt/master.py", line 871, in _handle_signals
    self.destroy(signum)
  File "/usr/lib/python3.9/site-packages/salt/master.py", line 932, in destroy
    self.process_manager.kill_children()
  File "/usr/lib/python3.9/site-packages/salt/utils/process.py", line 703, in kill_children
    p_map["Process"].join(0)
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 39, in wait
    from multiprocessing.connection import wait
  File "/usr/lib/python3.9/site-packages/salt/master.py", line 871, in _handle_signals
    self.destroy(signum)
  File "/usr/lib/python3.9/site-packages/salt/master.py", line 932, in destroy
    self.process_manager.kill_children()
  File "/usr/lib/python3.9/site-packages/salt/utils/process.py", line 703, in kill_children
    p_map["Process"].join(0)
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 39, in wait
    from multiprocessing.connection import wait
ImportError: cannot import name 'wait' from partially initialized module 'multiprocessing.connection' (most likely due to a circular import) (/usr/lib64/python3.9/multiprocessing/connection.py)
```

**Comment by sbluhm** [comment]
`2023-06-21 14:00:00,613 [tornado.application:353 ][ERROR   ][4136974] Future <salt.ext.tornado.concurrent.Future object at 0x7f1ac546f5e0> exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/salt/ext/tornado/gen.py", line 309, in wrapper
    yielded = next(result)
  File "/usr/lib/python3.9/site-packages/salt/utils/process.py", line 631, in run
    time.sleep(10)
  File "/usr/lib/python3.9/site-packages/salt/master.py", line 871, in _handle_signals
    self.destroy(signum)
  File "/usr/lib/python3.9/site-packages/salt/master.py", line 932, in destroy
    self.process_manager.kill_children()
  File "/usr/lib/python3.9/site-packages/salt/utils/process.py", line 703, in kill_children
    p_map["Process"].join(0)
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 39, in wait
    from multiprocessing.connection import wait
  File "/usr/lib/python3.9/site-packages/salt/master.py", line 871, in _handle_signals
    self.destroy(signum)
  File "/usr/lib/python3.9/site-packages/salt/master.py", line 932, in destroy
    self.process_manager.kill_children()
  File "/usr/lib/python3.9/site-packages/salt/utils/process.py", line 703, in kill_children
    p_map["Process"].join(0)
  File "/usr/lib64/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python3.9/multiprocessing/popen_fork.py", line 39, in wait
    from multiprocessing.connection import wait
ImportError: cannot import name 'wait' from partially initialized module 'multiprocessing.connection' (most likely due to a circular import) (/usr/lib64/python3.9/multiprocessing/connection.py)
`

**Comment by sbluhm** [comment]
not sure what this is anymore and havent seen it lately. so closing
