### ISSUE TITLE
Upgrade from 2023.09 to 2023.10 now tomcat won't start

### ISSUE THREAD

**Issue by ChrisN812** [sbluhm/uyuni#126]
### Problem description

Did an upgrade of the OS (RHEL 9.3) and Uyuni to 2023.10, tomcat has error starting after mgr-setup -s

28-Nov-2023 14:15:59.227 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to initialize component [Connector[AJP/1.3-8009]]

### Steps to reproduce

1.
2.
3.
...

### Uyuni version

```bash
Uyuni Version: 2023.10
OS: RedHat 9.3
```

**Comment by ChrisN812** [comment]
28-Nov-2023 14:15:59.227 SEVERE [main] org.apache.catalina.util.LifecycleBase.handleSubClassException Failed to initialize component [Connector[AJP/1.3-8009]]
        org.apache.catalina.LifecycleException: Protocol handler initialization failed
                at org.apache.catalina.connector.Connector.initInternal(Connector.java:1049)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.core.StandardService.initInternal(StandardService.java:556)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1042)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:724)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:746)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:305)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475)
        Caused by: java.net.SocketException: Protocol family unavailable
                at java.base/sun.nio.ch.Net.bind0(Native Method)
                at java.base/sun.nio.ch.Net.bind(Net.java:459)
                at java.base/sun.nio.ch.Net.bind(Net.java:448)
                at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
                at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:274)
                at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:229)
                at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1227)
                at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1240)
                at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:603)
                at org.apache.catalina.connector.Connector.initInternal(Connector.java:1046)
                ... 13 more

**Comment by sbluhm** [comment]
@ChrisN812 , I am trying to follow what you have done.
1. What is the reason you ran `mgr-setup -s` again? Won't that wipe your data?
2. If you intend to wipe your data, why did you run the upgrade?

Can you check if all symlinks are there there and valid via
`find /usr/share/tomcat/webapps/rhn/WEB-INF/lib -xtype l`

Maybe try to re-run the patch file:
`curl https://raw.githubusercontent.com/sbluhm/uyuni-repo/master/patch-2023.10.sh | bash # Installs current fixes`

**Comment by ChrisN812** [comment]
Thanks for the attention:

This is my 'test' environment, I want to get away from OpenSUSE (business decision),  and I do not have anything real in this instance anyway.

# find /usr/share/tomcat/webapps/rhn/WEB-INF/lib -xtype l
<< nothing found >>

# curl https://raw.githubusercontent.com/sbluhm/uyuni-repo/master/patch-2023.10.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1289  100  1289    0     0   7859      0 --:--:-- --:--:-- --:--:--  7859
ln: failed to create symbolic link '/srv/susemanager/susemanager': File exists
mkdir: cannot create directory ‘/usr/share/java/javassist/’: File exists
ln: failed to create symbolic link '/usr/share/java/javassist/javassist.jar': File exists
Java RHN logging in /usr/share/tomcat/webapps/rhn/WEB-INF/classes/log4j2.xml

**Comment by sbluhm** [comment]
If you do a tomcat restart (`systemctl restart tomcat`), does it work now?
If you want the easy way, install the system from scratch directly onto branch 2023.10. That one should work straight away.

In the meantime, let me check if my system has any issues with an update. Haven't done it yet.

**Comment by sbluhm** [comment]
I just updated my system from AlmaLinux 9.2 to 9.3 and at the same time from Uyuni 2023.09 to 2023.10. Everything loads up fine. Just had to do a CTRL+F5 to hard load and show the lists on systems or salt keys.

Can you send me your full log? Feel free to e-mail it to me via `ws2011` at `bluhm-de.com`

**Comment by ChrisN812** [comment]
> I just updated my system from AlmaLinux 9.2 to 9.3 and at the same time from Uyuni 2023.09 to 2023.10. Everything loads up fine. Just had to do a CTRL+F5 to hard load and show the lists on systems or salt keys.
> 
> Can you send me your full log? Feel free to e-mail it to me via `ws2011` at `bluhm-de.com`

Thanks for the help. Eventually i just started over with a clean RHEL 9.2 system and fresh Uyuni install of 2023.10

Everything is syncing and updating normally now.
