### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.12 - Taskomatic unable to find repo2solv.sh

### ISSUE THREAD

**Issue by lumarel** [sbluhm/uyuni#49]
After the successful installation of Uyuni I noticed the following errors in the system journal:
```bash
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]: java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/repo2solv.sh": error=2, No such file or directory
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at com.redhat.rhn.taskomatic.task.repomd.RpmRepositoryWriter.generateSolv(RpmRepositoryWriter.java:452)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at com.redhat.rhn.taskomatic.task.repomd.RpmRepositoryWriter.writeRepomdFiles(RpmRepositoryWriter.java:424)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at com.redhat.rhn.taskomatic.task.repomd.ChannelRepodataWorker.run(ChannelRepodataWorker.java:114)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(PooledExecutor.java:732)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.Thread.run(Thread.java:829)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]: Caused by: java.io.IOException: Cannot run program "/usr/bin/repo2solv.sh": error=2, No such file or directory
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.Runtime.exec(Runtime.java:592)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.Runtime.exec(Runtime.java:494)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at com.redhat.rhn.taskomatic.task.repomd.RpmRepositoryWriter.generateSolv(RpmRepositoryWriter.java:442)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         ... 4 more
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]: Caused by: java.io.IOException: error=2, No such file or directory
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
Dec 08 16:57:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         ... 8 more
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]: java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/repo2solv.sh": error=2, No such file or directory
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at com.redhat.rhn.taskomatic.task.repomd.RpmRepositoryWriter.generateSolv(RpmRepositoryWriter.java:452)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at com.redhat.rhn.taskomatic.task.repomd.RpmRepositoryWriter.writeRepomdFiles(RpmRepositoryWriter.java:424)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at com.redhat.rhn.taskomatic.task.repomd.ChannelRepodataWorker.run(ChannelRepodataWorker.java:114)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at EDU.oswego.cs.dl.util.concurrent.PooledExecutor$Worker.run(PooledExecutor.java:732)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.Thread.run(Thread.java:829)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]: Caused by: java.io.IOException: Cannot run program "/usr/bin/repo2solv.sh": error=2, No such file or directory
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.Runtime.exec(Runtime.java:592)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.Runtime.exec(Runtime.java:494)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at com.redhat.rhn.taskomatic.task.repomd.RpmRepositoryWriter.generateSolv(RpmRepositoryWriter.java:442)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         ... 4 more
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]: Caused by: java.io.IOException: error=2, No such file or directory
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
Dec 08 16:58:00 r8-uyuni-dev.30.fritz.box taskomatic[42094]:         ... 8 more
```

And yes the file is really missing:
```bash
# ll /usr/bin/repo2solv.sh
ls: cannot access '/usr/bin/repo2solv.sh': No such file or directory
```

Further searched on the system to make sure the file isn't just in a different directory, but no luck.

Was looking at a running production system, and it looks that is part of the package `libsolv-tools` on openSUSE. (`# /usr/bin/repo2solv.sh -> repo2solv`)
This package is also available in the EL 8 world, but isn't installed by default or after the Uyuni installation and on the other hand only has /usr/bin/repo2solv in it but not the symlink to repo2solv.sh

**Comment by sbluhm** [comment]
Also can't find libsolv-tools as a package dependency in the Uyuni spec files. So not sure if mandatory or not.

On EL8:
```
# dnf provides repo2solv
libsolv-tools-0.7.19-1.el8.x86_64 : Package dependency solver tools
Quelle      : powertools
Übereinstimmung von:
Dateiname     : /usr/bin/repo2solv
```

On Leap, package contains:
```
/usr/bin/repo2solv
/usr/bin/repo2solv.sh
```

**Comment by lumarel** [comment]
If I see this correctly in my logs and failing functionality, the build of Content Lifecycles doesn't complete because of this.
This is from one of the already over 9000 log files created from the `channel-repodata-bunch`:
```
2021-12-08 18:26:00,048 [DefaultQuartzScheduler_Worker-1] INFO  com.redhat.rhn.taskomatic.task.ChannelRepodata  - In the queue: 1
2021-12-08 18:26:00,060 [Thread-1893] WARN  com.redhat.rhn.taskomatic.task.ChannelRepodata  - NOT processing channel(rockylinux8-x86_64-appstream) because another thread is already working on run
2021-12-08 18:27:00,033 [DefaultQuartzScheduler_Worker-9] INFO  com.redhat.rhn.taskomatic.task.ChannelRepodata  - In the queue: 1
2021-12-08 18:27:00,043 [Thread-1901] WARN  com.redhat.rhn.taskomatic.task.ChannelRepodata  - NOT processing channel(rockylinux8-x86_64-appstream) because another thread is already working on run
2021-12-08 18:28:01,696 [DefaultQuartzScheduler_Worker-17] INFO  com.redhat.rhn.taskomatic.task.ChannelRepodata  - In the queue: 1
2021-12-08 18:28:01,735 [Thread-1909] WARN  com.redhat.rhn.taskomatic.task.ChannelRepodata  - NOT processing channel(rockylinux8-x86_64-appstream) because another thread is already working on run
2021-12-08 18:29:00,053 [DefaultQuartzScheduler_Worker-18] INFO  com.redhat.rhn.taskomatic.task.ChannelRepodata  - In the queue: 3
2021-12-08 18:29:00,074 [Thread-1918] WARN  com.redhat.rhn.taskomatic.task.ChannelRepodata  - NOT processing channel(rockylinux8-x86_64-appstream) because another thread is already working on run
2021-12-08 18:29:13,800 [Thread-1917] ERROR com.redhat.rhn.taskomatic.task.ChannelRepodata  - java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/repo2solv.sh": error=2, No such file or directory
2021-12-08 18:29:32,232 [Thread-1918] ERROR com.redhat.rhn.taskomatic.task.ChannelRepodata  - java.lang.RuntimeException: java.io.IOException: Cannot run program "/usr/bin/repo2solv.sh": error=2, No such file or directory
```

**Comment by sbluhm** [comment]
How are you reproducing/noticing this issue? I never noticed any issues despite this warning. I synced channels.

**Comment by lumarel** [comment]
You need to create a Content Lifecycle, the normal syncing of channels with their underlying Repositories works 👌🏻
![image](https://user-images.githubusercontent.com/42647570/145454800-e742dee3-0070-4ec6-85bd-b512cfad6507.png)

This is to create multiple versions of the same repos, to roll out packages in Tiers:
![image](https://user-images.githubusercontent.com/42647570/145455013-21ddab29-9595-423b-8611-0d459c71afcc.png)
