### ISSUE TITLE
reposync fails on uid

### ISSUE THREAD

**Issue by sbluhm** [sbluhm/uyuni#5]
/usr/bin/spacewalk-repo-sync --channel centos8-baseos-x86_64 --type yum --non-interactive

2021/01/02 13:44:29 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'centos8-baseos-x86_64', '--type', 'yum', '--non-interactive', '--sync-kickstart']
2021/01/02 13:44:29 +02:00 Sync of channel started.
2021/01/02 13:44:29 +02:00 Unhandled error occurred: uid should be integer, not NoneType
2021/01/02 13:44:29 +02:00 Unexpected error: <class 'TypeError'>
2021/01/02 13:44:29 +02:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 570, in sync
    client_key_file=client_key_file)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 462, in __init__
    self.repo = ZypperRepo(root=root, url=self.url, org=self.org)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 160, in __init__
    fileutils.makedirs(self.root, user='wwwrun', group='www')
  File "/usr/lib/python3.6/site-packages/uyuni/common/fileutils.py", line 265, in makedirs
    os.chown(dirname, uid, gid)
TypeError: uid should be integer, not NoneType

**Comment by sbluhm** [comment]
Hardcoded user...
https://github.com/sbluhm/uyuni/blob/2958336f7c24b6aec6ed5f1b391399c2ac8afbf9/backend/satellite_tools/repo_plugins/yum_src.py#L160
https://github.com/sbluhm/uyuni/blob/2958336f7c24b6aec6ed5f1b391399c2ac8afbf9/backend/satellite_tools/repo_plugins/yum_src.py#L162

**Comment by sbluhm** [comment]
done
