### ISSUE TITLE
Uyuni Bugreport - Uyuni 2021.12 - new yum_dnf_repo plugin is unable to sync mirrorlist

### ISSUE THREAD

**Issue by lumarel** [sbluhm/uyuni#50]
## Steps to reproduce

- Run `spacewalk-common-channels -a x86_64 rockylinux8 rockylinux8-appstream rockylinux8-uyuni-client` or similar command for AlmaLinux
- This will create the repos with the mirrorlist as the source
- Run the reposync either via the UI or spacecmd

## Additional information

The following errors will be visible in the log (example for BaseOS):
```bash
2021-12-08 15:04:15,068 [DefaultQuartzScheduler_Worker-17] INFO  com.redhat.rhn.taskomatic.task.RepoSyncTask  - Syncing repos for channel: RockyLinux 8 (x86_64)
2021-12-08 15:04:17,600 [Thread-272] ERROR com.redhat.rhn.taskomatic.task.RepoSyncTask  - WARNING:dnf:Errors during downloading metadata for repository 'External_-_RockyLinux_8_x86_64_':
  - Status code: 404 for https://mirrors.rockylinux.org/mirrorlist/repodata/repomd.xml?repo=BaseOS-8&arch=x86_64 (IP: 199.232.18.132)

2021-12-08 15:04:17,600 [Thread-271] INFO  com.redhat.rhn.taskomatic.task.RepoSyncTask  - 15:04:15 ======================================
15:04:15 | Channel: rockylinux8-x86_64
15:04:15 ======================================
15:04:15 Sync of channel started.
15:04:17 Unhandled error occurred: Failed to download metadata for repo 'External_-_RockyLinux_8_x86_64_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
15:04:17 Unexpected error: <class 'dnf.exceptions.RepoError'>
15:04:17 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 574, in load
    ret = self._repo.load()
  File "/usr/lib64/python3.6/site-packages/libdnf/repo.py", line 397, in load
    return _repo.Repo_load(self)
libdnf._error.Error: Failed to download metadata for repo 'External_-_RockyLinux_8_x86_64_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_dnf_src.py", line 214, in setup_repo
    self.yumbase.repos[self.repoid].load()
  File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 581, in load
    raise dnf.exceptions.RepoError(str(e))
dnf.exceptions.RepoError: Failed to download metadata for repo 'External_-_RockyLinux_8_x86_64_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 574, in load
    ret = self._repo.load()
  File "/usr/lib64/python3.6/site-packages/libdnf/repo.py", line 397, in load
    return _repo.Repo_load(self)
libdnf._error.Error: Failed to download metadata for repo 'External_-_RockyLinux_8_x86_64_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 576, in sync
    channel_arch=self.channel_arch)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_dnf_src.py", line 151, in __init__
    self.setup_repo(repo, no_mirrors, ca_cert_file, client_cert_file, client_key_file)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_dnf_src.py", line 222, in setup_repo
    self.dnfbase.repos[self.repoid].load()
  File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 581, in load
    raise dnf.exceptions.RepoError(str(e))
dnf.exceptions.RepoError: Failed to download metadata for repo 'External_-_RockyLinux_8_x86_64_': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

15:04:17 Total time: 0:00:02
```

After changing from the mirrorlist source to a direct server (i.e. `https://dl.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os/`) it worked flawlessly!

**Comment by sbluhm** [comment]
Setting `no_mirrors = false` in https://github.com/uyuni-project/uyuni/blob/ecdd0283d163d007f281bcd58fed655ef11fc90d/backend/satellite_tools/repo_plugins/yum_dnf_src.py#L74 makes it work.
So have to figure out how/why/when/where this should be set.

...
```
14:43:01     Syncing 319 new patch(es) to channel.
14:43:04   Regenerating bootstrap repositories.
Generating bootstrap repos for all available products which had changes.
Nothing to do.
14:43:05 Sync completed.
14:43:05 Total time: 0:05:48

```

**Comment by sbluhm** [comment]
https://github.com/uyuni-project/uyuni/pull/4588
