### ISSUE TITLE
reposync should use dnf

### ISSUE THREAD

**Issue by sbluhm** [sbluhm/uyuni#6]
/usr/bin/spacewalk-repo-sync --channel centos8-baseos-x86_64 --type yum --non-interactive

14:36:03 ======================================
14:36:03 | Channel: centos8-baseos-x86_64
14:36:03 ======================================
14:36:03 Sync of channel started.
sh: zypper: Kommando nicht gefunden.
14:36:03 RepoMDError: Cannot access repository. Maybe repository GPG keys are not imported
14:36:03 Total time: 0:00:00

Update backend to dnf instead of zypper (as getting zypper to run will cause conflicts with the libsolv requirements)

**Comment by sbluhm** [comment]
download fails for dnf and zypper due to 
`ERROR: Download failed: https://mirror.scaleuptech.com/centos/8/BaseOS/x86_64/os/Packages/ModemManager-glib-1.10.8-2.el8.i686.rpm - [Errno 14] curl#1 - "Protocol "b'https" not supported or disabled in libcurl".`

Somewhere in the code there is a str() of a byte array of url. this converts b'url' to the string "b'url'"

**Comment by sbluhm** [comment]
21:49:27 Unexpected error: <class 'UnicodeDecodeError'>
21:49:27 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 592, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1064, in import_packages
    downloader.run()
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/download.py", line 354, in run
    raise self.exception  # pylint: disable=E0702
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/download.py", line 231, in __fetch_url
    checksum=params['checksum']):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/download.py", line 167, in __is_file_done
    return getFileChecksum(checksum_type, file_obj=file_obj) == checksum
  File "/usr/lib/python3.6/site-packages/uyuni/common/checksum.py", line 79, in getFileChecksum
    buf = f.read(buffer_size)
  File "/usr/lib/python3.6/site-packages/urlgrabber/grabber.py", line 1969, in read
    self._fill_buffer(amt)
  File "/usr/lib/python3.6/site-packages/urlgrabber/grabber.py", line 1909, in _fill_buffer
    new = self.fo.read(readamount)
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 0: invalid continuation byte

**Comment by sbluhm** [comment]
CentOS uses urlgrabber 4. Uyuni urlgrabber 3. This sorts the curl protocol issue without code changes,

**Comment by sbluhm** [comment]
CentOS uses urlgrabber 4. Uyuni urlgrabber 3. This sorts the curl protocol issue without code changes.

**Comment by sbluhm** [comment]
```
# /usr/bin/spacewalk-repo-sync --channel repotest --type yum --non-interactive
10:33:16 ======================================
10:33:16 | Channel: repotest
10:33:16 ======================================
10:33:16 Sync of channel started.
10:33:18 Repo URL: https://github.com/sbluhm/spacewalk-support/raw/master/packages/
10:33:18     Packages in repo:                 1
10:33:18     Packages already synced:          0
10:33:18     Packages to sync:                 1
10:33:18     New packages to download:         1
10:33:18   Downloading packages:
10:33:18 Downloading total 1 files from 1 queues.
10:33:18     1/1 : jgit-5.4.0-6.fc30.noarch.rpm
10:33:18 
10:33:18   Importing packages to DB:
10:33:18 Unexpected error: <class 'TypeError'>
10:33:18 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 592, in sync
    ret = self.import_packages(plugin, data['id'], url, is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1078, in import_packages
    affected_channels_batch, failed_packages_batch, all_packages, processed_batch = result.get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 210, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Package objects

```

**Comment by sbluhm** [comment]
Delta DNF/Zypper:
dnf: 'epoch': 0
zypper: 'epoch': ''
dnf: 'unique_id': <hawkey.Package object id 2, jgit-5.4.0-6.fc30.noarch, repotest>
zypper: 'unique_id': RawSolvablePackage(jgit-5.4.0-6.fc30.noarch)

**Comment by sbluhm** [comment]
Works now. get_updates needed fixing and adding of additional suse functions.
Kickstart fails:
`/usr/bin/spacewalk-repo-sync --channel centos8-baseos-x86_64 --type yum --non-interactive --sync-kickstart`

```
2021/01/13 22:37:48 +02:00   Importing kickstarts.
2021/01/13 22:37:48 +02:00 Unexpected error: <class 'AttributeError'>
2021/01/13 22:37:48 +02:00 Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 615, in sync
    self.import_kickstart(plugin, data['repo_label'], is_non_local_repo)
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/reposync.py", line 1602, in import_kickstart
    treeinfo = plug.get_file(path, os.path.join(plug.repo.basecachedir, plug.name))
  File "/usr/lib/python3.6/site-packages/spacewalk/satellite_tools/repo_plugins/yum_src.py", line 708, in get_file
    downloaded = self.repo.grab.urlgrab(path, temp_file)
  File "/usr/lib/python3.6/site-packages/dnf/conf/config.py", line 67, in __getattr__
    option = getattr(self._config, name)
  File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 1682, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, ConfigRepo, name)
  File "/usr/lib64/python3.6/site-packages/libdnf/conf.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'ConfigRepo' object has no attribute 'grab'

2021/01/13 22:37:49 +02:00   Regenerating bootstrap repositories.

```

**Comment by sbluhm** [comment]
Same issue for zypper. Therefore done.
